language: ruby
rvm:
  - 2.0.0
  - 2.1.1
env:
  - DB=mysql
before_script:
  - 
  - mysql -e 'create database `kyoko-san_test`;'
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake spec
notifications:
  on_success: always
  on_failure: always
